#!/bin/bash
#job name: you can change it
#PBS -N test
#Queue for GPU nodes: do NOT change it
#PBS -q gpu
#1 nodes x 2 processes
#PBS -l nodes=1:ppn=2

#echo "I am a PBS job!"

echo "Nodefile generated by pbs system:"
echo `cat $PBS_NODEFILE`

NPROCS=`wc -l < $PBS_NODEFILE`
echo "Number of processors (cores) used: $NPROCS"

#Gundolf
/shared/pgi/linux86/12.10/bin/../mpi/mpich/bin/mpirun -machinefile $PBS_NODEFILE -v -np 2 /work/users/ghaase/Gyoer_12/templates/OpenACC/par_skalar/main.MPI_PGI_

echo "Finished!"