#!/bin/sh

#PBS -N cklhexps
#PBS -l nodes=16:ppn=4

set numNodes=16
set workersPerNode=16
set numProcesses=64 # 64 nodes *4 processes per node = 256 processes
set vecSize=1000000000
set numChares=1
set numCharesPerPE=1
set staticFraction=0.00
set chunkSize=1

set opt= 0 # implementation strategy - OpenMP vs CkLoop VS vSched.

for vecSize in 2^28; do
    echo "Running experiments for dot product code with vector size $vecSize per node."
    for numCharesPerPE in 1 2 4 8 16; do
	for staticFraction in 0.00 0.125 0.25 0.375 0.50 0.625 0.75 0.875 1.00; do
	    for chunkSize in 1 2 4 8 128; do
                #  for opt in 0 1 2 3; do
		   time ibrun -n 64 ./dotProd $vecSize $numCharesPerPE $staticFraction $chunkSize $opt ++ppn $workersPerNode
		done
	    done
	done
    done
done